image: ruby:3.2

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

stages:
  - test
  - build
  - deploy
  - export

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - main

# Optional deploy to Gitlab pages (e.g. for staging)
# pages:
#   stage: pages
#   script:
#     - bundle exec jekyll build -d public --config _config.yml,_config_pages.yml
#   artifacts:
#     name: pages
#     paths:
#       - public
#   only:
#     - main

build:
  stage: build
  script:
    - bundle exec jekyll build -d _site --config _config.yml
  artifacts:
    name: _site
    paths:
      - _site
  only:
    - main

deploy:
 stage: deploy
 image: "registry.gitlab.vgiscience.org/tud_ifk/rsync-ssh-alpine:alpine3.17-r0-v4"
 before_script:
 - eval $(ssh-agent -s)
 - echo "${SSH_PRIVKEY}" | ssh-add -
 - mkdir -p ~/.ssh
 - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\tLogLevel QUIET\n\n" > ~/.ssh/config'
 script:
 - rsync -avu -zz --no-perms --omit-dir-times --chown=www-data:www-data --chmod=D775,F664 _site/ "${PRODUCTION_DESTINATION}"/public/sample-presentation/
 only:
   - main

# Optional manual PDF generation via DeckTape Docker
# only triggers on manual builds
export_pdf:
  stage: export
  image:
    name: astefanutti/decktape:latest
    entrypoint: [""]
  before_script: []
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
      allow_failure: true
  script:
    # 1. Read baseurl dynamically from _config.yml (e.g. /sample-presentation)
    - SLIDE_PATH=$(grep '^baseurl:' _config.yml | cut -d ':' -f 2 | tr -d ' "'\' | tr -d '\r')
    # 2. Run DeckTape using the resolved path
    - node /decktape/decktape.js reveal "https://slides.ad.ioer.info${SLIDE_PATH}/" presentation.pdf --size 1280x700 --pause 5500 --load-pause 3000 --chrome-path chromium-browser --chrome-arg=--no-sandbox
  artifacts:
    name: "presentation-pdf-${CI_COMMIT_SHORT_SHA}"
    paths:
      - presentation.pdf
    expire_in: 3 months