theme: ioer-presentation-theme

# the presentation title
title: IOER Presentation Template

firstslide-title: Welcome
firstslide-subtitle: .. to the IOER example web presentation  
firstslide-author: <br>with RevealJS!

controls: true # direction arrows in the presentation
progress: true # progress bar
center: true # center vertically
width: 1280 # widescreen 1280, classic 960
transition: fade # none/fade/slide/convex/concave/zoom

baseurl: / # adjust to the path of your presentation

# Don't change anything below
markdown: kramdown
markdown_ext: ignore
